import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne, Bebas_Neue } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";
import "./globals.css";
import Nav from "@/components/Nav";

import { syne, bebasNeue, inter } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bebasNeue.variable} ${syne.variable} ${inter.variable} max-w-screen`}
      >
        <div
          id="portal-root"
          className="fixed inset-0 w-full h-full overflow-hidden pointer-events-none [&>*]:pointer-events-auto"
          aria-hidden
          style={{ zIndex: 9998 }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
